WARNING: path= was not specified but multiple tables are present, reading in first available table (path=abmatched_halos.hdf5) [astropy.io.misc.hdf5]
slurmstepd: error: _get_pss: ferror() indicates error on file /proc/30251/smaps
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
/home/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py:444: UserWarning: One value for r is outside the bounds (0.096, 33.997) of the emulator.
  pname, plow, phigh))
slurmstepd: error: *** JOB 19478729 ON sh-2-15 CANCELLED AT 2018-01-09T23:37:30 DUE TO TIME LIMIT ***
