/home/users/swmclau2/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[sh-30-31:75832] *** Process received signal ***
[sh-30-31:75832] Signal: Segmentation fault (11)
[sh-30-31:75832] Signal code: Address not mapped (1)
[sh-30-31:75832] Failing at address: 0x28dbc10
[sh-30-31:75833] *** Process received signal ***
[sh-30-31:75833] Signal: Segmentation fault (11)
[sh-30-31:75833] Signal code: Address not mapped (1)
[sh-30-31:75833] Failing at address: 0x28dbc10
[sh-30-31:75834] *** Process received signal ***
[sh-30-31:75834] Signal: Segmentation fault (11)
[sh-30-31:75834] Signal code: Address not mapped (1)
[sh-30-31:75834] Failing at address: 0x28dbc10
[sh-30-31:75835] *** Process received signal ***
[sh-30-31:75835] Signal: Segmentation fault (11)
[sh-30-31:75835] Signal code: Address not mapped (1)
[sh-30-31:75835] Failing at address: 0x28dbc10
[sh-30-31:75862] *** Process received signal ***
[sh-30-31:75862] Signal: Segmentation fault (11)
[sh-30-31:75862] Signal code: Address not mapped (1)
[sh-30-31:75862] Failing at address: 0x28dbc10
[sh-30-31:75864] *** Process received signal ***
[sh-30-31:75864] Signal: Segmentation fault (11)
[sh-30-31:75864] Signal code: Address not mapped (1)
[sh-30-31:75864] Failing at address: 0x28dbc10
Traceback (most recent call last):
  File "/home/users/swmclau2/Git/pearce/bin/optimization/cosmo_bayesian_optimizer.py", line 18, in <module>
    emu = OriginalRecipe(training_file, method = em_method, fixed_params=fixed_params, downsample_factor = 1.0, custom_mean_function = 'linear')
  File "/home/users/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py", line 76, in __init__
    self.load_training_data(filename, custom_mean_function)
  File "/home/users/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py", line 308, in load_training_data
    x, y, ycov = self.get_data(filename, self.fixed_params, self.independent_variable, attach_params=True)
  File "/home/users/swmclau2/.local/lib/python2.7/site-packages/pearce/emulator/emu.py", line 102, in get_data
    assert path.isfile(filename)
AssertionError
